default: &default
  adapter: postgresql
  encoding: unicode
  username: quiz_app
  password: test123
  pool: 5

development:
  <<: *default
  database: quiz_app_development

test:
  <<: *default
  database: quiz_app_test

production:
  <<: *default
  database: quiz_app_production
  username: quiz_app
  password: <%= ENV['QUIZ_APP_DATABASE_PASSWORD'] %>
